### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [gingerbeardman/monkey.tmbundle#7]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing CC-BY would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by gingerbeardman** [comment]
Sure, I'll switch it soon.

**Comment by gingerbeardman** [comment]
Changed to MIT license. 

Thanks for asking and for using this as part of GitHub!

**Comment by arfon** [comment]
> Thanks for asking and for using this as part of GitHub!

:zap: many thanks!
